apiVersion: apps/v1
kind: Deployment
metadata:
  name: ayvcodr-api
  namespace: ayvcodr
spec:
  template:
    spec:
      containers:
      - name: ayvcodr-api
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"